language: node_js
node_js:
  - '8'

# Test and build the project
script:
  - npm run clean
  - npm run lint
  - npm test
  - npm run build

# Only run builds on master
branches:
  only:
    - master

# Cache node_modules npm and sonar for faster builds
cache:
  directories:
    - "$HOME/.npm"
    - "./node_modules"

notifications:
  email: false
